#!/bin/sh
#$ -cwd
#$ -l short
#$ -t 1
#$ -e ./logs/
#$ -o ./logs/
#$ -l gpus=1
python main.py --cuda --epochs 6 --tied
python generate.py
python main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 40 --tied
python generate.py
python main.py --cuda --emsize 1500 --nhid 1500 --dropout 0.65 --epochs 40 --tied
python generate.py
